# Dathaton FIAP - PASSOS MÁGICOS

## Importing Libraries

In [8]:
%%capture
# hide output, exclude the line above if you want to see the output of this installation
!pip install pycaret

In [9]:
from dotenv import load_dotenv

import os
from pathlib import Path

import pandas as pd
import numpy as np

# from pycaret.classification import setup, compare_models, predict_model, tune_model, finalize_model, plot_model, evaluate_model, save_model, load_model
import pycaret.classification as pc
# pc = pycaret.classification

import psycopg2

import plotly.express as px
import plotly.graph_objects as go

## Connecting to Database

In [10]:
# Getting the database variables from the .env file
load_dotenv()

DB_KEY = os.getenv("DB_KEY")
DB_NAME = os.getenv("DB_NAME")

In [11]:
# Connecting to the database
conn = psycopg2.connect(
    dbname='PEDE_PASSOS',
    user=DB_NAME,
    host='localhost',
    port='5432',
    password=DB_KEY)

## Loading Data

In [12]:
# Reading the data from the database
data = pd.read_sql("SELECT * FROM pede_passos.students_grades", con=conn)

## Preprocessing Data

In [13]:
# The selection of database columns is necessary, as some preprocessing and grouping have already been conducted in KNIME, 
# allowing me the flexibility to incorporate additional columns later
treated_data = data[['NOME', 'ANO', 'FASE', 'IAA', 'IAN', 'IDA', 'IEG', 'IPP', 'IPS', 'IPV',
       'INDE', 'PEDRA']]

# Due to inconsistent criteria, the 'NOME' column is removed, as the previous and new databases differ in this respect
treated_data = data.drop(columns=['NOME'], axis=1, errors='ignore')

# Adjusting 'FASE' column values
treated_data.loc[treated_data['ANO']=='2020', 'FASE'] = treated_data.loc[treated_data['ANO']=='2020', 'FASE'].str[:-1]
treated_data.loc[treated_data['ANO']=='2021', 'FASE'] = treated_data.loc[treated_data['ANO']=='2021', 'FASE'].str[:-2]
treated_data.loc[treated_data['ANO']=='2022', 'FASE'] = treated_data.loc[treated_data['ANO']=='2022', 'FASE'].str[:-2]
treated_data.loc[treated_data['ANO']=='2024', 'FASE'] = treated_data.loc[treated_data['ANO']=='2024', 'FASE'].str[:-1]
treated_data['FASE'] = treated_data['FASE'].str.replace('FASE ', '')
treated_data['FASE'] = treated_data['FASE'].str.replace(r'ALF.*', '0', regex=True)

# The column 'ANO'can be removed as well using the same logic as the 'NOME' column
treated_data = treated_data.drop(columns=['ANO'], axis=1, errors='ignore')

In [14]:
# Converting columns to numeric
columns_to_adj = ['IAA', 'IAN', 'IDA', 'IEG', 'IPP', 'IPS', 'IPV', 'INDE']
for col in columns_to_adj:
	treated_data[col] = treated_data[col].str.replace(',', '.')

for col in treated_data.columns[:-1]:
	treated_data[col] = pd.to_numeric(treated_data[col], errors='coerce')

# Adjusting 'PEDRA' column values
pedras = ['Quartzo', 'Ágata', 'Ametista', 'Topázio']

treated_data['PEDRA'] = treated_data['PEDRA'].str.replace('Agata', 'Ágata')
treated_data['PEDRA'] = treated_data['PEDRA'].apply(lambda x: x if x in pedras else np.nan)

In [15]:
# Segregating scholars data from academic data as the criteria for the definition of PEDRA is different
# Creating new columns for the scholars' data, where 0 means the student is a scholar and 1 means the student is a academic
treated_data['STUDENT'] = treated_data['FASE'].apply(lambda x: 0 if x < 8 else 1)
treated_data.drop(columns=['FASE'], inplace=True)

# Since the academic data only covers 2020 and includes just 24 entries, I'm excluding it from this analysis for now
treated_data = treated_data[treated_data['STUDENT'] == 0].drop(columns=['STUDENT'])

In [16]:
# Removing invalid data values
treated_data = treated_data.dropna(how='any', subset=['PEDRA'])
treated_data = treated_data.dropna(thresh=6).reset_index(drop=True)

# Converting 'FASE' column to integer
# treated_data['FASE'] = treated_data['FASE'].astype(int)

In [17]:
# Adjusting the 'PEDRA' column values to numericla to fit the model
category_pedras = {
    'Quartzo': 0,
    'Ágata': 1,
    'Ametista': 2,
    'Topázio': 3
}

treated_data['PEDRA'] = treated_data['PEDRA'].map(category_pedras)

In [18]:
# Removing INDE column as for a Simulator this indicator would not be available
treated_data.drop(columns='INDE', inplace=True)

## Data Modeling

In [19]:
clf = pc.setup(data=treated_data, target='PEDRA', session_id=123, experiment_name='Previsão de Pedra Conceito', verbose=False)
description = pc.pull()

best_model = pc.compare_models(sort='F1', verbose=False)
metrics = pc.pull()

tuned_model = pc.tune_model(best_model, verbose=False)
fold = pc.pull()

final_model = pc.finalize_model(tuned_model)

In [20]:
pc.save_model(final_model, '../models/lr_pedra_classification', model_only=True)

Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['IAA', 'IAN', 'IDA', 'IEG', 'IPP',
                                              'IPS', 'IPV'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='mean'))),
                 ('categorical_imputer',
                  TransformerWrapper(exclude=None, include=[...
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='most_frequent'))),
                 ('actual_estimator',
                  LogisticRegression(C=8.866, class_weight='balanced',
                                     dual=False, fit_intercept=True,
                                     intercept_scaling=1, l1_ratio=None,
                                     max_iter=1000, multi_class='auto',
                                     n_jobs=None, penalty='l2', random_state=123,
                                     solver='lbfgs', tol=0.0001, verbose=0,
                                     warm_start=False))],
          verbose=False),
 '../models/lr_pedra_classification.pkl')

In [21]:
predictions = pc.predict_model(tuned_model)

## Visualization

In [22]:
from sklearn.metrics import confusion_matrix

In [23]:
cm = confusion_matrix(predictions['PEDRA'], predictions['prediction_label'])

fig = px.imshow(cm, 
                labels=dict(x="Predito", y="Real", color="Contagem"),
                x=['Quartzo', 'Ágata', 'Ametista', 'Topázio'],
                y=['Quartzo', 'Ágata', 'Ametista', 'Topázio'],
                text_auto=True,
                color_continuous_scale='gnbu')

fig.update_layout(
    # title="Matriz de Confusão Interativa",
                  width=600,
                  height=600,
                )
fig.show()

In [24]:
discrete_colors = ['#ffa600',
'#374c80',
'#7a5195',
'#bc5090',
'#ef5675',
'#ff764a',
'#ffa600']

In [25]:
# Obter as importâncias das features
feature_importance = np.abs(tuned_model.coef_[0])

# Criar dataframe com as importâncias
df_importance = pd.DataFrame({
    'Feature': tuned_model.feature_names_in_,
    'Importance': feature_importance
}).sort_values(by="Importance", ascending=False)

# Criar gráfico de barras interativo
fig = px.bar(df_importance, x='Importance', y='Feature', 
            orientation='h', 
            #  title="Importância das Features",
            color='Importance', 
            color_continuous_scale='aggrnyl',
            template='plotly_white',
            text_auto=True
            )

fig.update_layout(
                  width=800,
                  height=500,
                )

fig.update_traces(
    marker=dict(reversescale=True),
    texttemplate='%{x:.2f}')

fig.show()

In [26]:
treated_data

           IAA   IAN  IDA  IEG      IPP    IPS       IPV  PEDRA
0      8.50002  10.0  7.0  8.7  5.93750  7.500  7.750000      2
1      7.50000   5.0  8.8  6.3  7.70000  6.900  8.100000      2
2      5.83333  10.0  0.0  5.2  7.96875  3.750  6.833333      0
3      9.00002   5.0  7.5  6.5  6.87500  4.375  7.916665      1
4      8.50000   5.0  0.0  0.0  6.30000  3.800  3.800000      0
...        ...   ...  ...  ...      ...    ...       ...    ...
4229   8.80000  10.0  6.2  9.7  7.50000  6.300  7.500000      2
4230   6.70000  10.0  5.5  9.7  7.50000  6.600  7.500000      2
4231  10.00000  10.0  2.6  9.9  7.50000  6.900  7.500000      2
4232   8.30000  10.0  8.3  9.2  7.50000  6.600  7.500000      3
4233   7.50000  10.0  6.4  9.6  7.50000  5.900  7.500000      2

[4234 rows x 8 columns]

In [27]:
import pandas as pd
fases = {
        '1º ano': ('Alfa', 7), '2º ano': ('Alfa', 8),
        '3º ano': ('Fase 1', 8), '4º ano': ('Fase 1', 9),
        '5º ano': ('Fase 2', 10), '6º ano': ('Fase 2', 11),
        '7º ano': ('Fase 3', 12), '8º ano': ('Fase 3', 13),
        '9º ano': ('Fase 4', 14), '1º EM': ('Fase 5', 15),
        '2º EM': ('Fase 6', 16), '3º EM': ('Fase 7', 17),
        'Universidade': ('Fase 8', 18)
    }

fase = pd.DataFrame(fases)

fase

,1º ano,2º ano,3º ano,4º ano,5º ano,6º ano,7º ano,8º ano,9º ano,1º EM,2º EM,3º EM,Universidade
0,Alfa,Alfa,Fase 1,Fase 1,Fase 2,Fase 2,Fase 3,Fase 3,Fase 4,Fase 5,Fase 6,Fase 7,Fase 8
1,7,8,8,9,10,11,12,13,14,15,16,17,18

In [28]:
pc.evaluate_model(final_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…